name: surebook
description: "Effortlessly book your next consultation with a sleek and intuitive appointment system, designed for a seamless user experience on both iOS and Android."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  video_player: ^2.10.0
  http: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/D.jpg" # your icon file
flutter:
  uses-material-design: true

  assets:
    - assets/splash.mp4
    - assets/man.png
    - assets/doctor.jpg
    - assets/D.jpg

    
